version: '3'
services:
  campaign:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=campaign-db
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PWD}
      - RABBITMQ_HOST=amqp
    ports:
      - ${CAMPAIGNS_PORT}:8080
      - ${CAMPAIGNS_DEBUG_PORT}:5005

  campaign-db:
    image: postgres:12.5
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:7.3
    depends_on:
      - campaign-db
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://campaign-db/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate

  amqp:
    image: rabbitmq:3.9-management
    expose:
      - 5672
    ports:
      - ${RABBITMQ_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}

volumes:
  pg_data:
    driver: local